language: ruby
rvm:
- 2.5.1
addons:
  postgresql: '9.6'
cache:
  bundler: true
  directories:
    - vendor/bundle
    - $HOME/.rvm/gems
install:
  - bundle install
before_script:
  - psql -c 'create database ouijabot;' -U postgres
script:
 - bundle install
 - bundle exec rubocop
 - bundle exec rake
