name: Rubocop

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Run Rubocop
      run: bundle exec rubocop -c .rubocop.yml -P
